FROM php:8.2-fpm

# composerのインストール
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# パッケージのインストール
RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    tzdata \
    zip \
    unzip \
    libpq-dev
RUN docker-php-ext-install pdo_mysql 
RUN docker-php-ext-install pdo_pgsql 
RUN rm -rf /var/lib/apt/lists/*

# タイムゾーンを設定する環境変数
ENV TZ="Asia/Tokyo"
